### ISSUE TITLE
bug: IGDB search is missing results shown on the main site and other bots

### ISSUE THREAD

**Issue by ghost** [skyra-project/skyra#545]
**Describe the bug**
Certain games refuse to show up using the `s!igdb` command despite being searchable with the [reference bot](https://gitlab.com/SirRandall/Bender) (hosted in the IGDB discord server) and the [main search page](https://www.igdb.com/search).

**To Reproduce**
1. `s!igdb Guilty Gear`
2. Observe error

**Expected behavior**
Game was found by the bot and shown in the results

**Screenshots**

![image](https://user-images.githubusercontent.com/7173984/69030886-c4d90700-09a6-11ea-9be6-61e671fc598f.png)

![image](https://user-images.githubusercontent.com/7173984/69030830-a5da7500-09a6-11ea-947e-ea387a865120.png)

**Additional context**
Similar issue in ribbon bot.

**Comment by ghost** [comment]
I wonder if this is related to everyone getting the paid tier for free now
![image](https://user-images.githubusercontent.com/7173984/69057309-9af00680-09df-11ea-8a2e-85efb3bbba3f.png)

**Comment by kyranet** [comment]
No, the "WTF" (**W**hat a **T**errible **F**ailure) errors are caused to an internal error we were not handling correctly.

In this case, the error is:

```javascript
RangeError [EMBED_FIELD_VALUE]: MessageEmbed field values may not be empty.
    at Function.checkField (/home/kyra/Skyra/node_modules/discord.js/src/structures/MessageEmbed.js:383:23)
    at MessageEmbed.addField (/home/kyra/Skyra/node_modules/discord.js/src/structures/MessageEmbed.js:201:39)
    at /home/kyra/Skyra/src/commands/Tools/Websearch/igdb.ts:101:6
    at UserRichDisplay._handlePageGeneration (/home/kyra/Skyra/node_modules/klasa/src/lib/util/RichDisplay.js:255:17)
    at UserRichDisplay.addPage (/home/kyra/Skyra/node_modules/klasa/src/lib/util/RichDisplay.js:165:24)
    at default_1.buildDisplay (/home/kyra/Skyra/src/commands/Tools/Websearch/igdb.ts:92:12)
    at default_1.run (/home/kyra/Skyra/src/commands/Tools/Websearch/igdb.ts:47:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at default_1.runCommand (/home/kyra/Skyra/src/monitors/commandHandler.ts:49:23)
```

It's not Skyra not having those entries because different tiers, but rather an error due to that specific entry not giving us the data we expected.

**Comment by kyranet** [comment]
Though another error came out too:

```typescript
TypeError: Cannot read property 'length' of undefined
    at Object.cutText (/home/kyra/Skyra/src/lib/util/util.ts:152:10)
    at /home/kyra/Skyra/src/commands/Tools/Websearch/igdb.ts:96:21
    at UserRichDisplay._handlePageGeneration (/home/kyra/Skyra/node_modules/klasa/src/lib/util/RichDisplay.js:255:17)
    at UserRichDisplay.addPage (/home/kyra/Skyra/node_modules/klasa/src/lib/util/RichDisplay.js:165:24)
    at default_1.buildDisplay (/home/kyra/Skyra/src/commands/Tools/Websearch/igdb.ts:92:12)
    at default_1.run (/home/kyra/Skyra/src/commands/Tools/Websearch/igdb.ts:47:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at default_1.runCommand (/home/kyra/Skyra/src/monitors/commandHandler.ts:49:23)
    at default_1._run (/home/kyra/Skyra/node_modules/klasa/src/lib/structures/Monitor.js:99:4)
```

**Comment by ghost** [comment]
https://github.com/igdb/igdb-typescript-types Not sure if this will be helpful since their types includes a lot more than the bot needs, but it looks like they had to change it recently to accommodate changes to the API.

**Comment by favna** [comment]
Types are published to NPM, we can include them as devDependency so @dependabot can notify us when they change. Good find. https://yarnpkg.com/en/package/@igdb/types
